version: '3.8'

services:
  api-what:
    build: .
    container_name: api-what
    expose:
      - "3001"
    restart: always

  nginx:
    # En vez de "nginx:alpine", usa una etiqueta Debian/Ubuntu
    # Por ejemplo, la versión stable:
    image: nginx:stable
    container_name: nginx-proxy
    depends_on:
      - api-what
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    restart: always
