version: '3.8'

services:
  api-what:
    build: .
    container_name: api-what
    ports:
      - "3001:3001"
    restart: always

  nginx:
    image: nginx:stable
    container_name: nginx-proxy
    depends_on:
      - api-what
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    restart: always
